### ISSUE TITLE
Production task list

### ISSUE THREAD

**Issue by bdb-dd** [Altinn/digdir-slack-bot#105]
### Description

Summary of tasks remaining before launch in altinndevops Slack workspace

```[tasklist]
### Tasks
- [x] Containerize for hosting as Container app
- [x] Deploy ColBERT reranking
- [x] Host ColBERT rerank service on GPU-enabled container
- [ ] https://github.com/Altinn/digdir-slack-bot/pull/117
- [x] Redeploy altinn_assistant to test workspace, prod test channels
- [x] Remove redundant Azure resources
- [x] Optimize remaining Azure resource usage
- [x] Refactor RAG stages to be configurable per stage (LLM name, temperature, etc)
- [ ] https://github.com/Altinn/digdir-assistants/issues/4
- [ ] https://github.com/Altinn/digdir-assistants/issues/5
- [ ] https://github.com/Altinn/digdir-assistants/issues/7
- [ ] https://github.com/Altinn/digdir-assistants/issues/6
```

```[tasklist]
### Tasks
```

**Comment by bdb-dd** [comment]
All necessary tasks completed, some remaining tasks transferred to new repo.
