### ISSUE TITLE
Add support for listening on one channel and speaking on another

### ISSUE THREAD

**Issue by bdb-dd** [Altinn/digdir-slack-bot#14]
### Description

During internal evaluation of various Slack bots, it is necessary to implement a human-in-the-loop workflow.

When HITL is active, the bot should not listen and reply on the same channel. 

Instead, it should support the following workflow:
- listen to incoming messages on any channel that the bot has been added to, referred to as `main channel`
- for each bot, if HITL configuration is active and valid, with a `review-channel-id`
  - send bot replies to `review` channel, with button actions for [send]

```[tasklist]
### Tasks
- [x] [doesn't work!] Add relevant metadata to bot replies so that the original thread and reply can be identified
- [x] Add "Send" button on message to allow for easy forwarding to `main`channel
- [x] Add support for processing emoji reaction events
- [x] Format bot replies to include button actions
- [x] Link `main`and `qa`channels manually
- [x] Add environment variable for specifying review channel ID
```

**Comment by bdb-dd** [comment]
Deployed to Altinn Assistent - TEST on Digdir AI slack workspace.
