### ISSUE TITLE
[DEMO] Studio Docs in Slack - demonstrate usage of OpenAI embeddings and RAG

### ISSUE THREAD

**Issue by bdb-dd** [Altinn/digdir-slack-bot#17]
### Description

Demonstrate effectiveness of custom system prompt together with Retrieval Augmented Prompting (RAG) context "stuffing".

### Use case
Slack bot monitors a specific channel and provides helpful information from Studio Docs training set in a new thread. 
Include link to the two most relevant sources in bot reply.

_No response_
```[tasklist]
### Tasks
- [x] Ingest Studio Docs
- [x] Generate OpenAI embeddings
- [x] Store embeddings in FAISS vector db
- [x] Use LangChain (Python) and ChatOpenAI retriever to stuff LLM query
- [x] Send query to OpenAI
- [x] Process result set, formatting source links to point to online version of Studio Docs
- [x] Send formatted result to Slack channel
- [x] Clean-up code base, double check licensing terms (MIT) and push to digdir-slack-bot repo
- [ ] [out of scope] Add feedback reactions to each documentation source item for Human Feedback Reinforcement Learning purposes
```

**Comment by bdb-dd** [comment]
Demo complete, functionality incorporated in [docs] bot
