### ISSUE TITLE
Add prompt continuation, requesting feedback on which source was most relevant for answering the query

### ISSUE THREAD

**Issue by bdb-dd** [Altinn/digdir-slack-bot#40]
Having pre-selected relevant content from available sources (docs.altinn.studio at the moment), we should gather feedback from GPT itself regarding which provided sources were most relevant when formulating a reply to the user. 

By collecting this feedback in Supabase, we can analyze it after the fact and expand our initial processing to include similarity search across user queries.
```[tasklist]
### Tasks
- [x] Add dedicated jsonb field in `bot_log` table for `llm_rag_feedback`
- [x] Change prompt chain to allow for manual context stuffing.
- [x] Modify prompt return schema to include a json formatted list of the relevant sources
- [x] Store results in `bot_log`
```

**Comment by bdb-dd** [comment]
Minimum viable ux included.
