### ISSUE TITLE
Add local embedding similarity score search to query pipeline

### ISSUE THREAD

**Issue by bdb-dd** [Altinn/digdir-slack-bot#55]
### Description

Typesense has support for storing vector embeddings as part of the same search index collection.

Now that we are manually stuffing the context window with retrieved documents, it should be straight forward to include the results of a similarity search.

### Tasks

- [x] Generate embeddings during index update
- [x] Add similarity search to RAG query pipeline
- [x] Add RRF if necessary
- [x] Evaluate results

**Comment by bdb-dd** [comment]
Similarity search deployed to test environment.

**Comment by bdb-dd** [comment]
ad-hoc testing shows some improvements, but more structured test method needed.
