### ISSUE TITLE
[rag] Make search phrase pipeline symmetric

### ISSUE THREAD

**Issue by bdb-dd** [Altinn/digdir-slack-bot#62]
### Description

Currently, we are using extracted search terms from the user query to search on the full text index of the entire documentation corpus. 

By generating search phrases for each documentation article, we can run hybrid text and vector search on the search phrases themselves.

This can be made to work across languages.

```[tasklist]
### Tasks
- [x] Generate search phrases for each article
- [x] Add multi-search stage to docs_qa pipeline
- [x] Verify sort and ranking for each stage, removing duplicates
- [x] Test results on historical queries
```

```[tasklist]
### Tasks
```
