### ISSUE TITLE
Setup and use production environments

### ISSUE THREAD

**Issue by bdb-dd** [Altinn/digdir-slack-bot#74]
### Description

Current setup will still be needed for test purposes, setup new environments for production

```[tasklist]
### Tasks
- [x] Setup hosted Typesense single-node cluster
- [x] Run scraper, search phrase generator job manually to seed indexes
- [x] Use environment vars
- [x] Create release branch in digdir-slack-bot repo
- [x] Configure Github actions for production deployment of digdir-slack-bot
- [x] Define production Slack app
- [x] Configure production Slack app to use "digdir-slack-bot" web app
- [x] Configure test Slack app to use new "digdir-slack-bot-test" web app
```

**Comment by bdb-dd** [comment]
All sub-tasks completed
